#!/usr/bin/env python3
"""
tools/verify_structures.py
===========================
Post-generation structural validator for MEIDNet-generated ABX3 perovskite CIFs.

Performs a battery of crystallographic and chemical checks on each CIF to
confirm that the generated structure represents a valid ideal cubic perovskite
in space group Pm-3m (#221):

    1. Stoichiometry  — exactly 5 sites: 1 A-site, 1 B-site, 3 X-site
    2. Cubic lattice  — a ≈ b ≈ c (within 5 %) and alpha = beta = gamma = 90 deg
                        (within 3 deg)
    3. Coordinate sanity — no NaN fractional coordinates
    4. Bond-length floor — minimum inter-site distance >= 0.8 A (no site collapse)
    5. Space-group check — pymatgen SpacegroupAnalyzer must report a cubic group
                           (number in range 195-230)

A structure passes only if all five criteria are met.

Usage
-----
    # Validate all CIFs in a single directory
    python tools/verify_structures.py --dir results/halide

    # Validate all three families generated by generate_candidates.py
    python tools/verify_structures.py --dir results/halide
    python tools/verify_structures.py --dir results/oxide
    python tools/verify_structures.py --dir results/chalcogenide
"""
import os, argparse, math, warnings
warnings.filterwarnings("ignore")

import numpy as np
from pymatgen.core import Structure
from pymatgen.io.cif import CifParser
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

ANIONS_ALL = {"O","F","Cl","Br","I","S","Se","Te","N"}
A_CATIONS  = {
    "Ba","Sr","Ca","Na","K","Rb","Cs",
    "La","Ce","Pr","Nd","Sm","Eu","Gd","Tb","Dy","Ho","Er","Tm","Yb","Lu"
}
B_CATIONS  = {
    "Ti","Zr","Hf","V","Nb","Ta","Cr","Mn","Fe","Co","Ni","Cu","Zn","Sc","Y",
    "Al","Ga","In","Ge","Sn","Pb","W","Mo"
}

CUBIC_ANGLE_TOL = 3.0     # degrees from 90
CUBIC_LAT_TOL   = 0.05    # fractional tolerance on a==b==c
HARD_MIN        = 0.8     # Å minimum inter-atomic distance


def check_cif(cif_path):
    issues = []
    try:
        parser = CifParser(cif_path)
        structs = parser.parse_structures(primitive=False)
        if not structs:
            return False, ["empty structure"]
        s = structs[0]
    except Exception as e:
        return False, [f"parse error: {e}"]

    # 1) site count == 5
    if len(s) != 5:
        issues.append(f"N_sites={len(s)} (expected 5 for ABX3)")

    # 2) composition check: 1 A, 1 B, 3 X
    syms = [site.specie.symbol for site in s]
    n_A = sum(1 for sym in syms if sym in A_CATIONS)
    n_B = sum(1 for sym in syms if sym in B_CATIONS)
    n_X = sum(1 for sym in syms if sym in ANIONS_ALL)
    if n_A != 1: issues.append(f"A-site count={n_A} (expected 1)")
    if n_B != 1: issues.append(f"B-site count={n_B} (expected 1)")
    if n_X != 3: issues.append(f"X-site count={n_X} (expected 3)")

    # 3) cubic lattice: a≈b≈c, α≈β≈γ≈90°
    latt = s.lattice
    a, b, c = latt.abc
    mean_a = (a + b + c) / 3.0
    if abs(a - b) / mean_a > CUBIC_LAT_TOL: issues.append(f"a≠b ({a:.3f} vs {b:.3f})")
    if abs(b - c) / mean_a > CUBIC_LAT_TOL: issues.append(f"b≠c ({b:.3f} vs {c:.3f})")
    for ang_name, ang_val in zip(("α","β","γ"), latt.angles):
        if abs(ang_val - 90.0) > CUBIC_ANGLE_TOL:
            issues.append(f"{ang_name}={ang_val:.2f}° (not cubic)")

    # 4) no NaN coords, no absurdly short bonds
    cart = s.cart_coords
    if np.isnan(cart).any():
        issues.append("NaN coordinates")
    else:
        N = cart.shape[0]
        min_d = min(
            np.linalg.norm(cart[i] - cart[j])
            for i in range(N) for j in range(i+1, N)
        ) if N > 1 else np.inf
        if min_d < HARD_MIN:
            issues.append(f"short bond: {min_d:.3f} Å < {HARD_MIN} Å")

    # 5) spacegroup should be cubic (number 195-230)
    try:
        sga = SpacegroupAnalyzer(s, symprec=0.1)
        sg_num = sga.get_space_group_number()
        if not (195 <= sg_num <= 230):
            issues.append(f"spacegroup #{sg_num} is not cubic (195-230)")
        else:
            issues.append(f"[info] spacegroup #{sg_num} cubic OK")
    except Exception as e:
        issues.append(f"spacegroup check failed: {e}")

    return (len([x for x in issues if not x.startswith("[info]")]) == 0), issues


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--dir", default="results_targetled", help="directory of generated CIF files")
    args = p.parse_args()

    cif_files = sorted(f for f in os.listdir(args.dir) if f.endswith(".cif"))
    if not cif_files:
        print(f"No CIF files found in {args.dir}")
        return

    passed, failed = 0, 0
    print(f"\n{'='*70}")
    print(f"Validating {len(cif_files)} generated CIF files in '{args.dir}'")
    print(f"{'='*70}")

    for fname in cif_files:
        fpath = os.path.join(args.dir, fname)
        ok, issues = check_cif(fpath)
        info_msgs = [x for x in issues if x.startswith("[info]")]
        err_msgs  = [x for x in issues if not x.startswith("[info]")]
        if ok:
            sg_info = info_msgs[0] if info_msgs else ""
            print(f"  PASS  {fname:<45} {sg_info}")
            passed += 1
        else:
            print(f"  FAIL  {fname}")
            for msg in err_msgs:
                print(f"        -> {msg}")
            failed += 1

    print(f"\n{'='*70}")
    print(f"RESULTS: {passed}/{passed+failed} CIF files pass all cubic-perovskite checks")
    print(f"  Passed: {passed}  |  Failed: {failed}")
    print(f"{'='*70}\n")


if __name__ == "__main__":
    main()
